import { Conversation } from '@/types/conversation';

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 1,
    publication_id: 103,
    other_user_name: 'Jean Dupont',
    other_user_avatar: 'https://i.pravatar.cc/150?u=1',
    last_message_content: 'Est-ce que le poste est toujours disponible ?',
    last_message_time: '14:30',
    unread_count: 2,
    status: 'active',
    is_pinned: false,
    publication_title: 'Développeur React Native',
  },
  {
    id: 2,
    publication_id: 103,
    other_user_name: 'Marie Lavoie',
    other_user_avatar: 'https://i.pravatar.cc/150?u=2',
    last_message_content: 'Merci, à demain !',
    last_message_time: 'Hier',
    unread_count: 0,
    status: 'active',
    is_pinned: true,
    publication_title: 'Développeur React Native',
  },
  {
    id: 3,
    publication_id: 103,
    other_user_name: 'Tech Solutions Inc.',
    other_user_avatar: 'https://i.pravatar.cc/150?u=3',
    last_message_content: 'Votre candidature a été retenue pour un entretien.',
    last_message_time: 'Lun.',
    unread_count: 1,
    status: 'active',
    is_pinned: false,
    publication_title: 'Développeur React Native',
  },
  {
    id: 4,
    publication_id: 104,
    other_user_name: 'Lucas Bernard',
    other_user_avatar: 'https://i.pravatar.cc/150?u=4',
    last_message_content: 'Je vous envoie le contrat par mail.',
    last_message_time: '09:15',
    unread_count: 0,
    status: 'active',
    is_pinned: false,
    publication_title: 'Développeur React Native',
  },
  {
    id: 5,
    publication_id: 104,
    other_user_name: 'Sophie Morel',
    other_user_avatar: 'https://i.pravatar.cc/150?u=5',
    last_message_content: "Désolé, j'ai eu un empêchement.",
    last_message_time: '12/05',
    unread_count: 0,
    status: 'active',
    is_pinned: false,
    publication_title: 'Développeur React Native',
  },
  {
    id: 6,
    publication_id: 104,
    other_user_name: 'BTP Services',
    other_user_avatar: 'https://i.pravatar.cc/150?u=6',
    last_message_content: 'Le chantier commence à 8h.',
    last_message_time: 'Mar.',
    unread_count: 5,
    status: 'active',
    is_pinned: false,
    publication_title: 'Développeur React Native',
  },
];
